version: '2'

services:
  web:
    image: 994642778742.dkr.ecr.us-east-1.amazonaws.com/tardibot/nginx:latest
    volumes_from:
      - app
    ports:
      - 80:80
    logging:
      driver: awslogs
      options:
        awslogs-group: tardibot
        awslogs-region: us-east-1
        awslogs-stream-prefix: tardibot
  fpm:
    image: php:7.2-fpm
    volumes_from:
      - app
    ports:
      - 9000:9000
    logging:
      driver: awslogs
      options:
        awslogs-group: tardibot
        awslogs-region: us-east-1
        awslogs-stream-prefix: tardibot
    environment:
      - SPOTIFY_CLIENT_ID
      - SPOTIFY_CLIENT_SECRET
      - GOOGLE_ACCESS_TOKEN
      - SLACK_TOKEN
      - APP_KEY
    working_dir: /app
  app:
    image: 994642778742.dkr.ecr.us-east-1.amazonaws.com/tardibot:$IMAGE_TAG
    logging:
      driver: awslogs
      options:
        awslogs-group: tardibot
        awslogs-region: us-east-1
        awslogs-stream-prefix: tardibot
